name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login --username=${{ secrets.DOCKER_USNER }} registry.cn-shenzhen.aliyuncs.com --password=${{ secrets.DOCKER_PASSWORD }}
        docker build . --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/houhou/uranus-music:${{ github.sha }}
        docker push registry.cn-shenzhen.aliyuncs.com/houhou/uranus-music:${{ github.sha }}
    # k8s部署
    - run: |
        sed -i 's/{TAG}/${{ github.sha }}/g' .deploy/deployment.yml
    - name: k8s deployment 
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        KUBECTL_VERSION: "1.14"
      with:
        args: apply -f .deploy/deployment.yml
    - name: k8s service
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        KUBECTL_VERSION: "1.14"
      with:
        args: apply -f .deploy/service.yml
    - name: deployment status
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        KUBECTL_VERSION: "1.14"
      with:
        args: '"rollout status deployment/uranus-music"'
